//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTalk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleTalk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleTalk.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно хочете видалити {0} з друзів ?.
        /// </summary>
        internal static string AskDeleteFriend {
            get {
                return ResourceManager.GetString("AskDeleteFriend", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap circle_green {
            get {
                object obj = ResourceManager.GetObject("circle_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle_red {
            get {
                object obj = ResourceManager.GetObject("circle_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося з&quot;єзднатися із сервером!.
        /// </summary>
        internal static string ErrorConnetingToServer {
            get {
                return ResourceManager.GetString("ErrorConnetingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалось виконати пошук! Можливо проблеми із з&quot;єднанням.
        /// </summary>
        internal static string ErrorGettingUsers {
            get {
                return ResourceManager.GetString("ErrorGettingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В доступі відмовлено! Можливо Ви ввели неправильну комбінацію логін/пароль або хтось вже використовує цей логін!.
        /// </summary>
        internal static string ErrorLogging {
            get {
                return ResourceManager.GetString("ErrorLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З&apos;єднання втрачено!.
        /// </summary>
        internal static string ErrorLostConnection {
            get {
                return ResourceManager.GetString("ErrorLostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Можливо ви не ввійшли до системи..
        /// </summary>
        internal static string ErrorMaybeUserNotConnected {
            get {
                return ResourceManager.GetString("ErrorMaybeUserNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля Логін та Пароль обов&apos;язково повинні бути заповненні!.
        /// </summary>
        internal static string ErrorRegistrationFields {
            get {
                return ResourceManager.GetString("ErrorRegistrationFields", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon google_talk {
            get {
                object obj = ResourceManager.GetObject("google_talk", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Історія повідомлень із {0}.
        /// </summary>
        internal static string msgHistory {
            get {
                return ResourceManager.GetString("msgHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детальна інформація про {0}.
        /// </summary>
        internal static string msgInformation {
            get {
                return ResourceManager.GetString("msgInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системне повідомлення : .
        /// </summary>
        internal static string msgSystem {
            get {
                return ResourceManager.GetString("msgSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} поза мережею. Тому отримає Ваші повідомлення, коли буде в мережі..
        /// </summary>
        internal static string msgUserOffline {
            get {
                return ResourceManager.GetString("msgUserOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви спілкуєтесь з {0}.
        /// </summary>
        internal static string txtConversationWith {
            get {
                return ResourceManager.GetString("txtConversationWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} хоче долучити Вас до друзів. Ви згодні ?.
        /// </summary>
        internal static string txtFriendRequest {
            get {
                return ResourceManager.GetString("txtFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш запит надіслано! Чекайте підтвердження від {0} .
        /// </summary>
        internal static string txtSentFriendRequest {
            get {
                return ResourceManager.GetString("txtSentFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} підтвердив ваш запит! Тепер ви друзі :).
        /// </summary>
        internal static string txtSuccessfulFriendRequest {
            get {
                return ResourceManager.GetString("txtSuccessfulFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успішне підключення!.
        /// </summary>
        internal static string txtSuccessfulLogin {
            get {
                return ResourceManager.GetString("txtSuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успішна реєстрація!.
        /// </summary>
        internal static string txtSuccessfulRegistration {
            get {
                return ResourceManager.GetString("txtSuccessfulRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін зайнятий іншим користувачем!.
        /// </summary>
        internal static string txtUserAlreadyExist {
            get {
                return ResourceManager.GetString("txtUserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хтось вже використовує цей логін!.
        /// </summary>
        internal static string txtUserAlreadyLogged {
            get {
                return ResourceManager.GetString("txtUserAlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А кому посилати запит ? Будь ласка виберіть Вашого майбутнього друга із списку!.
        /// </summary>
        internal static string WarningSendFriendRequest {
            get {
                return ResourceManager.GetString("WarningSendFriendRequest", resourceCulture);
            }
        }
    }
}
